### ISSUE TITLE
Uncaught (in promise) TypeError: this.client.createMediaMessageByUploading is not a function

### ISSUE THREAD

**Issue by wann2** [AgoraIO/RTM#115]
In Agora-RTM-Tutorial-Web,
When I try to send an image to channel or peer, I got the below error.

Uncaught (in promise) TypeError: this.client.createMediaMessageByUploading is not a function

**Comment by plutoless** [comment]
hi my guess is your rtm sdk version is too low. which version are you using?

**Comment by wann2** [comment]
I am using Agora_RTM_SDK_for_Web_1.4.1

**Comment by plutoless** [comment]
@wann2 
i tested again after upgrade package.json depencency to 1.4.1 and it's working, maybe try again
https://github.com/AgoraIO/RTM/commit/a297484bb6cfc86bd6b8c3c242ef72c413d578af

**Comment by shahzaib1010hassan** [comment]
Having Same issue in 1.5.1 Version. What will be solution of it??

**Comment by Rohit-1717** [comment]
In Agora-RTM-Tutorial-Web,
When I am trying to create the RTM instance I am getting this error "main.js:20 Uncaught (in promise) TypeError: AgoraRTM.createInstance is not a function",

I am using Signaling SDK version : 2.2.0

How can I fix that error ?

**Comment by SidhuAchary02** [comment]
@Rohit-1717 yes,
I am also having the same error while creating the RTM instance.
"Uncaught (in promise) TypeError: AgoraRTM.createInstance is not a function"

I am using the SDK Version`agora-rtm-sdk: ^2.2.1`

How can I fix it?

**Comment by MahmudunNabi140** [comment]
i want to implement  video call by  "agora-rtc-sdk-ng": "^4.22.1",
   the video call is work but  when i display all participate name then us this
 "agora-rtm-sdk": "^2.2.2",
but then not work .display this in console
I am also having the same error while creating the RTM instance.
"Uncaught (in promise) TypeError: AgoraRTM.createInstance is not a function

this is my joinwebinar.vue
<script setup>
import { ref, onMounted } from 'vue'
import { usePage } from '@inertiajs/vue3'
import AgoraRTC from 'agora-rtc-sdk-ng'
import AgoraRTM from 'agora-rtm-sdk'
import axios from 'axios'

const page = usePage()
const channelName = page.props.channelName
const isAdmin = page.props.isAdmin
const user = page.props.user
const APP_ID = '1a73c0bce126456fa757a6ee90766437'

const localVideo = ref(null)
const remoteUsersMap = ref({})
const userNameMap = ref({})
const isAudioMuted = ref(false)
const isVideoMuted = ref(false)
const isLoading = ref(false)

let agoraClient = AgoraRTC.createClient({ mode: 'rtc', codec: 'vp8' })
let audioTrack, videoTrack, uid
let rtmClient, rtmChannel

onMounted(async () => {
    uid = Math.floor(Math.random() * 100000)
    userNameMap.value[uid] = user.first_name

    // ✅ RTM Setup
    rtmClient = AgoraRTM.createInstance(APP_ID)
    await rtmClient.login({ uid: String(uid) })
    rtmChannel = await rtmClient.createChannel(channelName)
    await rtmChannel.join()

    // ✅ Broadcast your name
    await rtmChannel.sendMessage({ text: JSON.stringify({ uid, name: user.first_name }) })

    // ✅ Listen for others' names
    rtmChannel.on('ChannelMessage', ({ text }) => {
        const data = JSON.parse(text)
        if (data.uid && data.name) {
            userNameMap.value[data.uid] = data.name
            console.log(`Received name of user ${data.uid}: ${data.name}`)
        }
    })

    try {
        const res = await axios.post('/backend/video/token', {
            channelName,
            uid,
            role: 1,
        })

        const token = res.data.token
        await agoraClient.join(APP_ID, channelName, token, uid)

        audioTrack = await AgoraRTC.createMicrophoneAudioTrack()
        videoTrack = await AgoraRTC.createCameraVideoTrack()
        videoTrack.play(localVideo.value)
        await agoraClient.publish([audioTrack, videoTrack])

        agoraClient.on('user-published', async (user, mediaType) => {
            await agoraClient.subscribe(user, mediaType)
            playRemoteUser(user, mediaType)
        })

        agoraClient.on('user-unpublished', (user, mediaType) => {
            const el = document.getElementById(`remote-${user.uid}`)
            if (el) el.remove()
            delete remoteUsersMap.value[user.uid]
        })

        agoraClient.on('user-left', (user) => {
            const el = document.getElementById(`remote-${user.uid}`)
            if (el) el.remove()
            delete remoteUsersMap.value[user.uid]
        })

        agoraClient.remoteUsers.forEach(async user => {
            await agoraClient.subscribe(user, 'video')
            await agoraClient.subscribe(user, 'audio')
            playRemoteUser(user, 'video')
            playRemoteUser(user, 'audio')
        })

    } catch (err) {
        console.error('Join error:', err)
    }
})

function playRemoteUser(user, mediaType) {
    if (remoteUsersMap.value[user.uid]) return

    if (mediaType === 'video' && user.videoTrack) {
        const remoteVideo = document.createElement('div')
        remoteVideo.id = `remote-${user.uid}`
        remoteVideo.style = 'width: 300px; height: 200px; margin: 10px; background: #ddd; position: relative;'

        const displayName = userNameMap.value[user.uid] || `UID: ${user.uid}`
        console.log(`Remote user joined: ${displayName}`)

        remoteVideo.innerHTML =
            `<small style="position: absolute; bottom: 2px; left: 4px;">
                👤 ${displayName}
            </small>`

        document.getElementById('remote-container')?.appendChild(remoteVideo)
        user.videoTrack.play(remoteVideo)
        remoteUsersMap.value[user.uid] = true
    }

    if (mediaType === 'audio' && user.audioTrack) {
        user.audioTrack.play()
    }
}

async function leaveChannel() {
    isLoading.value = true
    try {
        if (audioTrack) await audioTrack.close()
        if (videoTrack) await videoTrack.close()
        await agoraClient.leave()

        if (rtmChannel) await rtmChannel.leave()
        if (rtmClient) await rtmClient.logout()

        window.close()
    } catch (err) {
        console.error('Leave error:', err)
    }
    isLoading.value = false
}
</script>


<template>
    {{ user.first_name }}
    <div style="padding: 20px;">
        <h2 class="webinar-title">🔗 Joined Channel: <strong>{{ channelName }}</strong></h2>
        <div style="text-align: center;">
            <p v-if="isAdmin">🧑‍🏫 <strong>You are the host (admin)</strong></p>
            <p v-else>👤 <strong>You are a participant</strong></p>
        </div>

        
        <div style="position: relative; margin-bottom: 10px;">
            <div ref="localVideo" class="video-box local-video"></div>
            <div style="margin-top: 10px; display: flex; gap: 10px;">
                <button class="control-button" @click="toggleAudio">
                    {{ isAudioMuted ? "Unmute Audio" : "Mute Audio" }}
                </button>
                <button class="control-button" @click="toggleVideo">
                    {{ isVideoMuted ? "Turn On Video" : "Turn Off Video" }}
                </button>
                <button class="control-button end-button" @click="leaveChannel" :disabled="isLoading">
                    {{ isLoading ? "Ending..." : "End Webinar" }}
                </button>
            </div>
        </div>

        
        <div id="remote-container" style="display: flex; flex-wrap: wrap;"></div>
    </div>
</template>

<style scoped>
.webinar-title {
    font-size: 24px;
    text-align: center;
    margin-bottom: 20px;
}

.video-box {
    flex: 1 1 calc(33.333% - 10px);
    max-width: calc(33.333% - 10px);
    height: 300px;
    background-color: black;
    border-radius: 6px;
    overflow: hidden;
}

.local-video {
    border: 2px solid #007bff;
}

.control-button {
    padding: 10px 20px;
    font-size: 16px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    background-color: #28a745;
    color: white;
}

.control-button:hover {
    background-color: #218838;
}

.end-button {
    background-color: #dc3545;
}

.end-button:hover {
    background-color: #c82333;
}
</style>

how i fix and display participate name
